# Generated by Django 3.2.7 on 2021-10-18 11:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
    ]
