# Generated by Django 3.2.7 on 2021-09-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whic_todo', to='todo.todo'),
        ),
    ]
