# Generated by Django 3.2.7 on 2021-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_category_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
