# Generated by Django 3.2.7 on 2021-10-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20211002_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whic_todo', to='todo.todo'),
        ),
    ]
